apiVersion: apps/v1
kind: Deployment
metadata:
  name: weather-forecasting-datadog
  labels:
    app: weather-forecasting-datadog
    env: prod
    service: weather-forecasting-datadog
spec:
  replicas: 1
  selector:
    matchLabels:
      app: weather-forecasting-datadog
  template:
    metadata:
      labels:
        app: weather-forecasting-datadog
        env: prod
        service: weather-forecasting-datadog
      annotations:
        ad.datadoghq.com/weather-forecasting-datadog.logs: '[{"source":"python","service":"weather-forecasting-datadog"}]'
    spec:
      containers:
      - name: weather-forecasting-datadog
        image: tejas8320/weather-forecasting-datadog:latest
        ports:
        - containerPort: 5000
        env:
        - name: DD_ENV
          value: "prod"
        - name: DD_SERVICE
          value: "weather-forecasting-datadog"
        - name: DD_VERSION
          value: "1.0.0"
        - name: DD_AGENT_HOST
          valueFrom:
            fieldRef:
              fieldPath: status.hostIP
        - name: DD_TRACE_AGENT_PORT
          value: "8126"
        - name: DD_LOGS_INJECTION
          value: "true"
        - name: PYTHONUNBUFFERED
          value: "1"
        volumeMounts:
        - name: dsdsocket
          mountPath: /var/run/datadog
      volumes:
      - name: dsdsocket
        hostPath:
          path: /var/run/datadog

