apiVersion: v1
kind: Service
metadata:
  name: weather-forecasting-datadog
spec:
  type: LoadBalancer
  selector:
    app: weather-forecasting-datadog
  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

